version: '3.7'
services:
  es-singlenode:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: es-singlenode
    environment:
        - xpack.security.enabled=false
        - node.name=single-node
        - cluster.name=kdsin
        - discovery.type=single-node
    ports:
        - 9200:9200
        - 9300:9300
    networks:
        - es-bridge
  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    container_name: docker-kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://es-singlenode:9200"]'
    ports:
      - 5601:5601
    expose:
      - 5601
    volumes:
    - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    networks:
        - es-bridge
networks:
    es-bridge:
        driver: bridge