version: "3.7"
services:
  docker-kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: docker-kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://host.docker.internal:9200"]'
    ports:
      - 5601:5601
    expose:
      - 5601
#    volumes:
#      - ./kibana-config.yml:/usr/share/kibana/config/kibana.yml
    restart: always
    network_mode: bridge

