filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /Users/sinkyoungdeok/Documents/github_code/elasticsearch/elasticsearch-7.12.0/logs/*.json

json.keys_under_root: true
json.add_error_key: true
json.message_key: log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.ilm.enabled: false
setup.template.enabled: false

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "http"
  index: "filebeat-es-%{+yyyy.MM.dd}"

#output.logstash:
  #hosts: ["localhost:5044"]

processors:
  - decode_json_fields:
      fields: ["message"]

