apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  containers:
  - name: hello-app
    image: yoonjeong/hello-app:1.0
    ports:
    - containerPort: 8080
    envFrom:
    - configMapRef:
        name: greeting-config-from-file
    env:
    - name: GREETING
      value: $(MESSAGE)! $(STUDENT_NAME)
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"